### ISSUE TITLE
You have to type /pv 1 2 times

### ISSUE THREAD

**Issue by OfficialLilKev** [IOTADevs/UltraVaults#1]

**Comment by OfficialLilKev** [comment]
02.01 00:33:41 [Server] Server thread/CRITICAL Error: "Call to a member function sendBlocks() on null" (EXCEPTION) in "UltraVaults-master/src/ultravaults/vault/VaultInventory" at line 74

**Comment by asyncthreading** [comment]
Works fine for me

**Comment by samuelctn** [comment]
agreed with @BajanVlogs  same error

**Comment by OfficialLilKev** [comment]
You gonna fix it or not

**Comment by TheAz928** [comment]
Unconfirmed bug isn't fixable
